### ISSUE TITLE
Integrate Existing Features into the `/build`

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#26]
# Goal

Integrate features from @theo-armour's feature folders into `/build`.

# Tasks

* [ ] integrate Mindmapping features
* [x] integrate Connect-edit features
* [x] integrate .stl loading features
